function AskForInput(Prompt)
global CObject 

FigPos = [0.413 0.45 0.15 0.1];  
FigColor=get(0,'DefaultUicontrolBackgroundColor');
C = get(0);%#ok

CObject.InptDLG = dialog(...
             'Units', 'Normalized',...
             'Position', FigPos,...
             'NumberTitle', 'off',...
             'Resize', 'off',...
             'Name','Enter Span:',...
             'Color',FigColor,...
             'MenuBar', 'none' );
         
SetFigIcon(CObject.InptDLG,'Radar.png');   
 
CObject.OK_Button = uicontrol(CObject.InptDLG,'Style','pushbutton',...
             'FontWeight','bold',... 
             'String','Ok',...
             'Units', 'Normalized',...
             'BackgroundColor',FigColor,...
             'Callback',{@GetSpan},...
             'Position',[0.52 0.022 .2 .2]);  
         
CObject.Cancel_Button = uicontrol(CObject.InptDLG,'Style','pushbutton',...
             'FontWeight','bold',... 
             'String','Cancel',...
             'Units', 'Normalized',...
             'BackgroundColor',FigColor,...
             'Callback',{@CanButton},...
             'Position',[0.75 0.022 0.2 0.2]);   
         
CObject.EBoxIn = uicontrol(CObject.InptDLG,'Style','edit',...
             'BackgroundColor','white',...
             'FontWeight','bold',...
             'FontSize',9, ...
             'String','150',...
             'Units', 'Normalized',...
             'HorizontalAlignment','left',...
             'Position',[0.1 0.55 0.75 0.15]); 
         
CObject.Prompt = uicontrol(CObject.InptDLG,'Style', 'text', ...
             'Units', 'Normalized',...
             'Position', [0.1 0.7 0.95 0.15], ...
             'FontSize', 9, ...
             'FontWeight', 'bold', ...
             'ForegroundColor','blue',...
             'BackgroundColor',FigColor,...
             'HorizontalAlignment','left',...
             'String',Prompt);         
         
return   

function CanButton(varargin)
global CObject

close(CObject.InptDLG);   

return
