function DisplayFHOPSettings(RL)
global CObject FigData 

 CObject.FHOPTitle = uicontrol(CObject.Pan1,'Style', 'text', ...
                   'Position', [10,RL,250,18], ...
                   'FontSize', 9, ...
                   'FontWeight', 'bold', ...
                   'ForegroundColor','blue',...
                   'BackgroundColor',FigData.Color,...
                   'HorizontalAlignment','left',...
                   'String','Frequency Hopping Settings..');  
    CObject.FHOPL = uicontrol(CObject.Pan1,'Style', 'edit', ...
                   'Position', [125,RL-25,50,20], ...
                   'FontSize', 8, ...
                   'BackgroundColor', 'white','Callback',@callbackfn);  
    CObject.FHOPLLabel = uicontrol(CObject.Pan1,'Style', 'text', ...
                   'Position', [10,RL-25,112,18], ...
                   'FontSize', 8, ...
                   'FontWeight', 'bold', ...
                   'BackgroundColor',FigData.Color,...
                   'HorizontalAlignment','left',...
                   'String','FRQ Hop Low (MHz):');
    CObject.FHOPH = uicontrol(CObject.Pan1,'Style', 'edit', ...
                   'Position', [125,RL-50,50,20], ...
                   'FontSize', 8, ...
                   'BackgroundColor', 'white','Callback',@callbackfn);  
    CObject.FHOPHLabel = uicontrol(CObject.Pan1,'Style', 'text', ...
                   'Position', [10,RL-50,112,18], ...
                   'FontSize', 8, ...
                   'FontWeight', 'bold', ...
                   'BackgroundColor',FigData.Color,...
                   'HorizontalAlignment','left',...
                   'String','FRQ Hop High (MHz):'); 
               
                    cm4 = uicontextmenu;
                    CObject.FHOPL.UIContextMenu = cm4;
                    txt(1)={'Enter lowest tuned frequency of hop set (MHz).'};
                    txt(2)={'For information only'};
                    txt(3)={'(optional field)'};
                    uimenu(cm4,'Label','Info','Callback',@Info_All,'UserData',txt)
                    cm5 = uicontextmenu;
                    CObject.FHOPH.UIContextMenu = cm5;
                    txt(1)={'Enter highest tuned frequency of hop set (MHz).'};
                    txt(2)={'For information only'};
                    txt(3)={'(optional field)'};
                    uimenu(cm5,'Label','Info','Callback',@Info_All,'UserData',txt)
                  
         
end

function callbackfn(source,~)
global AppData CObject

if source ==  CObject.FHOPH
AppData.FHOPH = CObject.FHOPH.String;
end

if source ==  CObject.FHOPL
AppData.FHOPL = CObject.FHOPL.String;
end

if isfield(AppData,'FHOPH')&& isfield(AppData,'FHOPL')
AppData.Bs = str2double(AppData.FHOPH) - str2double(AppData.FHOPL);    
end

end
                    
               
        