function LegacyTog(hObject, eventdata, handles)
global AppData CObject TraceLocker

if get(hObject,'Value') % 2020 off
   
   set(CObject.Legacy,'BackGroundColor',[0.3 0.75 0.93]); 
   set(TraceLocker.ProposedRSEC,'visible','off');
   
   if strcmp(get(AppData.hlegend,'visible'),'on') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'on') % Custom Mask on
        AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask,TraceLocker.CustomMask],AppData.RadarFName,...
   ['RSEC Mask ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],...
   ['Custom Mask ' num2str(AppData.CMxdb) 'dB/dec'],'Location','northeast');
   elseif strcmp(get(AppData.hlegend,'visible'),'on') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'off') % Custom Mask off
        AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask],AppData.RadarFName,...
   ['RSEC Mask ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],'Location','northeast');
   end
else
   set(CObject.Legacy,'BackGroundColor',[.87 .92 .98]); 
   set(TraceLocker.ProposedRSEC,'visible','on'); % 2020 on
   if strcmp(get(AppData.hlegend,'visible'),'on') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'on') % Custom Mask on
        AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask, TraceLocker.ProposedRSEC,TraceLocker.CustomMask],...
   AppData.RadarFName,['RSEC ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],...
   ['Proposed RSEC ' AppData.Criteria ' ' num2str(AppData.nSlope) 'dB/dec'],...
   ['Custom Mask ' num2str(AppData.CMxdb) 'dB/dec'],'Location','northeast');
   elseif strcmp(get(AppData.hlegend,'visible'),'on') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'off') % Custom Mask off
        AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask, TraceLocker.ProposedRSEC],AppData.RadarFName,...
   ['RSEC Mask ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],...
   ['Proposed RSEC ' AppData.Criteria ' ' num2str(AppData.nSlope) 'dB/dec'],'Location','northeast');
   end
end