function LegendTog(varargin)
global CObject AppData TraceLocker

hObject = varargin{1};

if get(hObject,'value')==0
   set(CObject.Legend,'BackGroundColor',[.87 .92 .98]);   
   if strcmp(get(TraceLocker.ProposedRSEC,'visible'),'on') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'on')
   AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask, TraceLocker.ProposedRSEC, TraceLocker.CustomMask],AppData.RadarFName,...
   ['RSEC Mask ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],...
   ['Proposed RSEC ' AppData.Criteria ' ' num2str(AppData.nSlope) 'dB/dec'],...
   ['Custom Mask ' num2str(AppData.CMslope) 'dB/dec'],'Location','northeast');

   elseif strcmp(get(TraceLocker.ProposedRSEC,'visible'),'on') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'off')
   AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask, TraceLocker.ProposedRSEC],AppData.RadarFName,...
   ['RSEC Mask ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],...
   ['Proposed RSEC ' AppData.Criteria ' ' num2str(AppData.nSlope) 'dB/dec'],'Location','northeast');

   elseif strcmp(get(TraceLocker.ProposedRSEC,'visible'),'off') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'on')
   AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask, TraceLocker.CustomMask],AppData.RadarFName,...
   ['RSEC Mask ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],...
   ['Custom Mask ' num2str(AppData.CMslope) 'dB/dec'],'Location','northeast');

   elseif strcmp(get(TraceLocker.ProposedRSEC,'visible'),'off') && strcmp(get(TraceLocker.CustomMask,...
           'visible'),'off')
   AppData.hlegend=legend([TraceLocker.UserData, TraceLocker.RSEC_Mask],AppData.RadarFName,...
   ['RSEC Mask ' AppData.Criteria ' ' num2str(AppData.oSlope) 'dB/dec'],'Location','northeast');
   end
else
   set(CObject.Legend,'BackGroundColor',[0.3 0.75 0.93]);  
   set(AppData.hlegend,'visible','off');
end